[auth]
ocs_user = snmp
ocs_password = snmp

[api]
ocs_base_url = http://127.0.0.1:8000

[scanner]
scanner_mode = OFFLINE
local_inventory_dir = /files
targeted_subnets = 
# can be INFO, DEBUG, WARNING, ERROR
log_level = DEBUG